name:                roar
version:             0.1.0.0
github:              "dclxvi13/roar"
license:             BSD3
author:              "dclxvi13"
maintainer:          "dclxvi.13.x@gmail.com"
copyright:           "Copyright (c) 2018 dclxvi13"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dclxvi13/roar#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  roar-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - roar

tests:
  roar-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - roar
